/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recaptcha_01;

import java.awt.Color;
import static java.awt.Color.*;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.BorderFactory;
import static javax.swing.BorderFactory.createLineBorder;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class mainFrame extends javax.swing.JFrame {
    private final HashSet<String> selectedLabels = new HashSet<>();
    //private final  ArrayList<String> correctLabels = new ArrayList<>();
    
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        //initializeIllegalLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lbl01 = new javax.swing.JLabel();
        lbl03 = new javax.swing.JLabel();
        lbl04 = new javax.swing.JLabel();
        lbl02 = new javax.swing.JLabel();
        lbl05 = new javax.swing.JLabel();
        lbl08 = new javax.swing.JLabel();
        lbl06 = new javax.swing.JLabel();
        lbl07 = new javax.swing.JLabel();
        lbl09 = new javax.swing.JLabel();
        cbNotRobot = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JButton();
        lblMain = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setBackground(new java.awt.Color(153, 204, 255));
        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("이 있는 타일을 모두 선택하세요");

        lbl01.setIcon(new javax.swing.ImageIcon("/Users/admin/Documents/스크린샷 2023-04-14 오후 10.37.33 복사본.png")); // NOI18N
        lbl01.setText("jLabel2");
        lbl01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl01MouseClicked(evt);
            }
        });

        lbl03.setIcon(new javax.swing.ImageIcon("/Users/admin/Documents/스크린샷 2023-04-14 오후 10.37.33 복사본.png")); // NOI18N
        lbl03.setText("jLabel2");
        lbl03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl03MouseClicked(evt);
            }
        });

        lbl04.setIcon(new javax.swing.ImageIcon("/Users/admin/Documents/스크린샷 2023-04-14 오후 10.37.33 복사본.png")); // NOI18N
        lbl04.setText("jLabel2");
        lbl04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl04MouseClicked(evt);
            }
        });

        lbl02.setIcon(new javax.swing.ImageIcon("/Users/admin/Documents/스크린샷 2023-04-14 오후 10.37.33 복사본.png")); // NOI18N
        lbl02.setText("jLabel2");
        lbl02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl02MouseClicked(evt);
            }
        });

        lbl05.setIcon(new javax.swing.ImageIcon("/Users/admin/Documents/스크린샷 2023-04-14 오후 10.37.33 복사본.png")); // NOI18N
        lbl05.setText("jLabel2");
        lbl05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl05MouseClicked(evt);
            }
        });

        lbl08.setIcon(new javax.swing.ImageIcon("/Users/admin/Documents/스크린샷 2023-04-14 오후 10.37.33 복사본.png")); // NOI18N
        lbl08.setText("jLabel2");
        lbl08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl08MouseClicked(evt);
            }
        });

        lbl06.setIcon(new javax.swing.ImageIcon("/Users/admin/Documents/스크린샷 2023-04-14 오후 10.37.33 복사본.png")); // NOI18N
        lbl06.setText("jLabel2");
        lbl06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl06MouseClicked(evt);
            }
        });

        lbl07.setIcon(new javax.swing.ImageIcon("/Users/admin/Documents/스크린샷 2023-04-14 오후 10.37.33 복사본.png")); // NOI18N
        lbl07.setText("jLabel2");
        lbl07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl07MouseClicked(evt);
            }
        });

        lbl09.setIcon(new javax.swing.ImageIcon("/Users/admin/Documents/스크린샷 2023-04-14 오후 10.37.33 복사본.png")); // NOI18N
        lbl09.setText("jLabel2");
        lbl09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl09MouseClicked(evt);
            }
        });

        cbNotRobot.setBackground(new java.awt.Color(204, 204, 204));
        cbNotRobot.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        cbNotRobot.setText(" 로봇이 아닙니다");
        cbNotRobot.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        cbNotRobot.setBorderPainted(true);
        cbNotRobot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnLogin.setBackground(new java.awt.Color(153, 204, 255));
        btnLogin.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnLogin.setText("로그인");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblMain.setBackground(new java.awt.Color(153, 204, 255));
        lblMain.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMain.setText("차량");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl01, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl02, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl03, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl04, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl05, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl06, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl07, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl08, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl09, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(cbNotRobot, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMain)
                .addGap(0, 0, 0)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl01, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl03, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl02, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl05, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl06, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl04, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl08, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl09, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl07, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNotRobot, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
         
    public HashSet<String> correctedLabels = new HashSet<>();
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(cbNotRobot.isSelected()){
            if (selectedLabels.containsAll(Arrays.asList("lbl01", "lbl02", "lbl04", "lbl08"))&& selectedLabels.equals(correctedLabels)){
                JOptionPane.showMessageDialog(null,"Welcome","Success", JOptionPane.PLAIN_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null,"틀렸습니다.\n당신은 사람이 맞습니까?","Err", JOptionPane.ERROR_MESSAGE);
        }
        }else{
            JOptionPane.showMessageDialog(null,"모든 프로세스를 적절하게 시행하시오","Err", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lbl01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl01MouseClicked
        if (lbl01.getBorder() == null) {
                lbl01.setBorder(BorderFactory.createLineBorder(BLUE, 5));
                selectedLabels.add("lbl01");
                correctedLabels.add("lbl01");
            } else {
                lbl01.setBorder(null);
                selectedLabels.remove("lbl01");
            }
    }//GEN-LAST:event_lbl01MouseClicked

    private void lbl02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl02MouseClicked
        if (lbl02.getBorder() == null) {
                lbl02.setBorder(BorderFactory.createLineBorder(BLUE, 5));
                selectedLabels.add("lbl02");
                correctedLabels.add("lbl02");
            } else {
                lbl02.setBorder(null);
                selectedLabels.remove("lbl02");
            }
    }//GEN-LAST:event_lbl02MouseClicked

    private void lbl03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl03MouseClicked
        if (lbl03.getBorder() == null) {
                lbl03.setBorder(BorderFactory.createLineBorder(BLUE, 5));
                selectedLabels.add("lbl03");
            } else {
                lbl03.setBorder(null);
                selectedLabels.remove("lbl03");
            }
    }//GEN-LAST:event_lbl03MouseClicked

    private void lbl04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl04MouseClicked
        if (lbl04.getBorder() == null) {
                lbl04.setBorder(BorderFactory.createLineBorder(BLUE, 5));
                selectedLabels.add("lbl04");
                correctedLabels.add("lbl04");
            } else {
                lbl04.setBorder(null);
                selectedLabels.remove("lbl04");
            }
    }//GEN-LAST:event_lbl04MouseClicked

    private void lbl05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl05MouseClicked
        if (lbl05.getBorder() == null) {
                lbl05.setBorder(BorderFactory.createLineBorder(BLUE, 5));
                selectedLabels.add("lbl05");
            } else {
                lbl05.setBorder(null);
                selectedLabels.remove("lbl05");
            }
    }//GEN-LAST:event_lbl05MouseClicked

    private void lbl06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl06MouseClicked
        if (lbl06.getBorder() == null) {
                lbl06.setBorder(BorderFactory.createLineBorder(BLUE, 5));
                selectedLabels.add("lbl06");
            } else {
                lbl06.setBorder(null);
                selectedLabels.remove("lbl06");
            }
    }//GEN-LAST:event_lbl06MouseClicked

    private void lbl07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl07MouseClicked
        if (lbl07.getBorder() == null) {
                lbl07.setBorder(BorderFactory.createLineBorder(BLUE, 5));
                selectedLabels.add("lbl07");
            } else {
                lbl07.setBorder(null);
                selectedLabels.remove("lbl07");
            }
    }//GEN-LAST:event_lbl07MouseClicked

    private void lbl08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl08MouseClicked
        if (lbl08.getBorder() == null) {
                lbl08.setBorder(BorderFactory.createLineBorder(BLUE, 5));
                selectedLabels.add("lbl08");
                correctedLabels.add("lbl08");
            } else {
                lbl08.setBorder(null);
                selectedLabels.remove("lbl08");
            }
    }//GEN-LAST:event_lbl08MouseClicked

    private void lbl09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl09MouseClicked
        if (lbl09.getBorder() == null) {
                lbl09.setBorder(BorderFactory.createLineBorder(BLUE, 5));
                selectedLabels.add("lbl09");
            } else {
                lbl09.setBorder(null);
                selectedLabels.remove("lbl09");
            }
    }//GEN-LAST:event_lbl09MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox cbNotRobot;
    private javax.swing.JList<String> jList1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl01;
    private javax.swing.JLabel lbl02;
    private javax.swing.JLabel lbl03;
    private javax.swing.JLabel lbl04;
    private javax.swing.JLabel lbl05;
    private javax.swing.JLabel lbl06;
    private javax.swing.JLabel lbl07;
    private javax.swing.JLabel lbl08;
    private javax.swing.JLabel lbl09;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    
}
